program: src/mlops_project/train.py
name: sweepdemo
project: corrupt_mnist  # change this
entity: mehmetyucelsaritas19-technical-university-of-munich  # change this
method: bayes
metric:
    goal: minimize
    name: validation_loss
parameters:
    lr:
        min: 0.0001
        max: 0.1
        distribution: log_uniform_values
    batch-size:
        values: [16, 32, 64]
    epochs:
        values: [5, 10, 15]
run_cap: 10